### ISSUE TITLE
weight norm removed during synthesis?

### ISSUE THREAD

**Issue by listener17** [yanggeng1995/FB-MelGAN#4]
Thanks for (sharing) the great work! If I see correctly, you remove the "weight_norm" during inference. Correct? In the original MelGAN do they also remove the "weight_norm" during inference?

**Comment by yanggeng1995** [comment]
In fact, the weight_norm was not removed during inference and the "remove_weight_norm" in Pytorch only the weight_g and weight_v were pre-calculated to reduce the amount of computation during inference。

**Comment by yanggeng1995** [comment]
> Thanks for (sharing) the great work! If I see correctly, you remove the "weight_norm" during inference. Correct? In the original MelGAN do they also remove the "weight_norm" during inference?

In fact, the weight_norm was not removed during inference。The  function of "remove_weight_norm" in Pytorch only calculates the weight_g and the weight_v in advance.
